api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from api import views

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token-obtain-pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('token/introspect/', views.TokenIntrospectView.as_view(), name='token-introspect'),
    path('dishes/', views.DishList.as_view(), name='dish-list'),
    path('dish/<int:pk>/', views.DishDetail.as_view(), name='dish-detail'),
    # path('restaurants/', views.RestaurantList.as_view(), name='restaurant-list'),
    # path('restaurant/<int:pk>/', views.RestaurantDetail.as_view(), name='restaurant-detail'),
    # path('menu/<int:pk>/', views.MenuDetail.as_view(), name='menu-detail'),
    path('restaurants/', views.RestaurantListCreateView.as_view(), name='restaurant-list-create'),
    path('restaurant/<int:pk>/', views.RestaurantRetrieveUpdateDestroyView.as_view(), name='restaurant-detail'),
    path('menus/', views.MenuListCreateView.as_view(), name='menu-list-create'),
    path('menu/<int:pk>/', views.MenuRetrieveUpdateDestroyView.as_view(), name='menu-detail'),
    path('orders/', views.OrderList.as_view(), name='order-list'),
    path('order/<int:pk>/', views.OrderDetail.as_view(), name='order-detail'),
    path('order_items/', views.OrderItemList.as_view(), name='order-item-list'),
    path('api/order_item/<int:pk>/', views.OrderItemDetail.as_view(), name='order-item-detail'),
]

from api import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('dishes/', views.DishList.as_view(), name='dish_list_create'),
    path('dishes/<int:pk>/', views.DishDetail.as_view(), name='dish_detail'),

    path('couriers/', views.CourierList.as_view(), name='courier_list_create'),
    path('couriers/<int:pk>/', views.CourierDetail.as_view(), name='courier_detail'),

    path('customers/', views.CustomerList.as_view(), name='customers_list_create'),
    path('customers/<int:pk>/', views.CustomerDetail.as_view(), name='customers_detail'),

    path('restaurants/', views.RestaurantList.as_view(), name='restaurant_list_create'),
    path('restaurants/<int:pk>/', views.RestaurantDetail.as_view(), name='restaurant_detail'),

    path('menus/', views.MenuList.as_view(), name='menu_list_create'),
    path('menus/<int:pk>/', views.MenuDetail.as_view(), name='menu_detail'),

    path('orders/', views.OrderListCreate.as_view(), name='order_list_create'),
    path('orders/<int:pk>/', views.OrderDetail.as_view(), name='order_detail'),

    path('order_items/', views.OrderItemListCreate.as_view(), name='order_item_list_create'),
    path('order_items/<int:pk>/', views.OrderItemDetail.as_view(), name='order_item_detail'),

    path('payments/', views.PaymentListCreate.as_view(), name='payment_list_create'),
    path('payments/<int:pk>/', views.PaymentDetail.as_view(), name='payment_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery_app/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("user.urls")),
    path('', include('store.urls')),
    path('api/', include('api.urls')),

    path('api/auth/', include('dj_rest_auth.urls')),
    path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('logout/', views.logout, name='logout'),
    path('settings/', views.profile_page, name='settings_page'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<slug:token>', views.reset_password, name='reset_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    avatar = models.ImageField(upload_to='user/', null=True, blank=False, default='img/profile.png')
    bio = models.TextField(max_length=2000, null=False, blank=True)
    resume = models.FileField(upload_to='user/', null=True, blank=True)
    owner = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        if self.owner.last_name:
            return f'{self.owner.first_name} {self.owner.last_name}'
        else:
            return f'{self.owner.username}'


class ResetPassword(models.Model):
    email = models.EmailField(null=False, blank=False, max_length=255)
    token = models.CharField(null=False, blank=False, max_length=255)
    created_at = models.DateTimeField(null=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Reset Password'
        verbose_name_plural = 'Reset Passwords'

    def __str__(self):
        return f'{self.id} {self.email} {self.token} {self.created_at}'

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile

RESET_PASSWORD_TOKEN_EXPIRATION_PERIOD = 3600

class LoginForm(forms.Form):
    username = forms.CharField(required=True, min_length=2, max_length=25,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(required=True, min_length=6, max_length=20,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        required=True,
        min_length=4,
        max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'placeholder': 'Enter your email'})
    )

class RegisterForm(forms.ModelForm):
    repeat_password = forms.CharField(required=True, min_length=6, max_length=20,
                                      widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Repeat your password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last name'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
        }

    def clean_repeat_password(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('repeat_password')
        if password1 and password2 and password1 != password2:
            raise ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class ResetPasswordForm(forms.Form):
    password = forms.CharField(
        required=True,
        min_length=8,
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'})
    )
    repeat_password = forms.CharField(
        required=True,
        min_length=8,
        max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Repeat your password'})
    )

    def clean_repeat_password(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("repeat_password")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match")
        return password2


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'Upload your avatar'})),
    resume = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'Upload your resume'})),
    class Meta:
        model = Profile
        fields = {'bio', 'avatar', 'resume'}
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your bio'}),
        }

user/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm, ProfileForm, ForgotPasswordForm, ResetPasswordForm
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from .models import Profile, ResetPassword
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.core.mail import send_mail
from django.conf import settings
from datetime import timezone
from django.contrib.auth.models import User
import uuid

RESET_PASSWORD_TOKEN_EXPIRATION_PERIOD = 3600

def login_page(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                auth_login(request, user)
                return redirect('/dishes/')
            form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()
    return render(request, 'user/login.html', {'form': form})

def register_page(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_data = authenticate(request, username=user.username, password=form.cleaned_data.get('password'))
            if auth_data:
                auth_login(request, auth_data)
                return redirect('/dishes/')
    else:
        form = RegisterForm()
    return render(request, 'user/register.html', {'form': form})

def logout(request):
    auth_logout(request)
    return redirect('/auth/login/')

@login_required
def profile_page(request):
    profile, created = Profile.objects.get_or_create(owner=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('settings_page')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'user/settings.html', {'form': form, 'profile': profile})


def forgot_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            token = uuid.uuid4()
            reset_password_entry, created = ResetPassword.objects.update_or_create(email=email, defaults={'token': token})
            email_template = loader.get_template('user/reset-password-mail.html')
            reset_link = f'http://localhost:8000/reset_password/{token}'
            email_content = email_template.render({'URL': reset_link, 'TOKEN': token})

            try:
                send_mail(
                    subject='Reset Your Password',
                    message='',
                    html_message=email_content,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[email],
                    fail_silently=False
                )
                return render(request, 'user/forgot-password.html', {'form': form, 'status': 'success'})
            except Exception as e:
                return render(request, 'user/forgot-password.html', {'form': form, 'status': 'failed', 'error': str(e)})
    else:
        form = ForgotPasswordForm()
    return render(request, 'user/forgot-password.html', {'form': form})

def reset_password(request, token):
    try:
        reset_password_entry = ResetPassword.objects.get(token=token)
        if (timezone.now() - reset_password_entry.created_at).total_seconds() > RESET_PASSWORD_TOKEN_EXPIRATION_PERIOD:
            reset_password_entry.delete()
            return render(request, 'user/reset-password.html', {'form': ResetPasswordForm(), 'message': 'Your link is expired, please try again!'})
    except ResetPassword.DoesNotExist:
        return render(request, 'user/reset-password.html', {'form': ResetPasswordForm(), 'message': 'Invalid or expired token!'})

    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            user = User.objects.get(email=reset_password_entry.email)
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            reset_password_entry.delete()
            return redirect('/auth/login/')
    else:
        form = ResetPasswordForm()

    return render(request, 'user/reset-password.html', {'form': form})

templates/user/forgot-password.html
{% extends 'base.html' %}
{% block title %}Forgot Password{% endblock %}
{% block content %}
<div>
    <form name="forgot_password" method="POST" novalidate class="password-form">
        <h1>Forgotten your password?</h1>
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label_tag }} {{ field }}
            <div class="errorlist">
                {{ field.errors }}
            </div>
        </div>
        {% endfor %}
        {% if status == 'success' %}
            <div role="alert" class="errorlist">
                The link has been sent to your email!
            </div>
        {% endif %}
        {% if status == 'failed' %}
            <div role="alert" class="errorlist">
                Something went wrong: {{ error }}.
            </div>
        {% endif %}
        <button type="submit">Send</button>
    </form>
</div>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
            <div class="login-container">
                <form name="login" method="POST" novalidate>
                    <h1>Login</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div>
                            {{ field.label_tag }}
                            {{ field }}
                            <div>
                                {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit">Sign In</button>
                    </form>
                <p>Don`t have account?<a class="exist" href="{% url 'register' %}">Sign Up</a></p>
                <p><a class="exist" href="{% url 'forgot_password' %}">Forgot your password?</a></p>
            </div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% block title %}Registration{% endblock %}
{% block content %}
            <div class="register-container">
                <form name="registration" method="POST">
                    <h1>Registration</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div>
                            {{ field.label_tag }}
                            {{ field }}
                            <div>
                                {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit">Sign Up</button>
                </form>
                <p>Already have an account?<a class="exist" href="{% url 'login' %}">Sign In</a></p>
            </div>
{% endblock %}

templates/user/reset-password-mail.html
<p>Hello,</p>
<p>You have requested to reset your password. Click the link below to reset it:</p>
<p><a href="http://localhost:8000/auth/reset_password/{{ TOKEN }}">Reset your password</a></p>
<p>If you didn't request this, please ignore this email.</p>

templates/user/reset-password.html
{% extends 'base.html' %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div>
    <form name="reset_password" method="POST" novalidate class="password-form">
        <h1>Reset Your Password</h1>
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label_tag }} {{ field }}
            <div class="errorlist">
                {{ field.errors }}
            </div>
        </div>
        {% endfor %}

        {% if status == 'success' %}
        <div class="alert alert-success">
            <p>Your password is reset successfully!</p>
        </div>
        {% endif %}

        {% if status == 'failed' %}
        <div class="alert alert-danger" role="alert">
            <p>Something went wrong!</p>
        </div>
        {% endif %}

        {% if message %}
        <div class="alert alert-warning" role="alert">
            <p>{{ message }}</p>
        </div>
        {% endif %}

        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock %}

templates/user/settings.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Settings{% endblock %}

{% block content %}
            <div>
                <h1>{% if user.first_name and user.last_name %} {{ user.first_name }} {{ user.last_name }}`s {% else %} {{ user.username }}`s {% endif %} profile settings</h1>
                <form method="POST" enctype="multipart/form-data" class="settings-form">
                    {% csrf_token %}
                    <div>
                        {% if profile.avatar %}
                            <img src="{{ profile.avatar.url }}" class="image_content"/>
                        {% endif %}
                        <label for="id_avatar">Upload your avatar here:</label>
                            <input id="id_avatar" class="file-profile" type="file" name="avatar" accept="image/*"/>
                        <div>
                            {{ form.avatar.errors }}
                        </div>
                    </div>
                    <div>
                        {{ form.bio.label_tag }} {{ form.bio }}
                        <div>
                            {{ form.bio.errors }}
                        </div>
                    </div>
                    <div>
                        <label for="id_resume">Upload your resume here:</label>
                        <input name="resume" class="file-profile" type="file" id="id_resume" accept="file/*">
                        <div>
                        {{ form.resume.errors }}
                        </div>
                        {% if profile.resume %}
                        <a class="exist" href="{{ profile.resume.url }}" target="_blank">Download</a>
                        {% endif %}
                    </div>
                    <button class="edit-profile" type="submit">Edit</button>
                </form>
            </div>
{% endblock %}